spring.datasource.url=jdbc:postgresql://localhost:5432/schoolconnect
spring.datasource.username=postgres
spring.datasource.password=naveed

# Optional but recommended
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA properties (optional, if you use JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
