DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS guardian CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS superadmin CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS role CASCADE;