# Use a lightweight JDK base image
FROM eclipse-temurin:17-jdk-alpine

# Argument to locate the JAR
ARG JAR_FILE=target/*.jar

# Copy the JAR file to the container
COPY ${JAR_FILE} app.jar

# Run the JAR
ENTRYPOINT ["java", "-jar", "/app.jar"]
